initial commit
architect-templates/nestjs pull request #1
Opened 2022-03-21 21:35 UTC by ryan-cahill

2022-03-21 22:12 UTC, tjhiggins requested changes

2022-03-21 22:12 UTC, tjhiggins commented on architect.yml
> +      DB_PORT: ${{ services.api-db.interfaces.postgres.port }}
remove

2022-03-21 22:12 UTC, tjhiggins commented on architect.yml
> +      DB_ADDR: ${{ services.api-db.interfaces.postgres.url }}/${{ parameters.api_db_name }}
Specify the db name as the path for the interface. Then you can simplify to:
```ts
DB_ADDR: ${{ services.api-db.interfaces.mysql.url }}
```

2022-03-21 22:12 UTC, tjhiggins commented on architect.yml
> +      postgres:
mysql

2022-03-22 17:27 UTC, ryan-cahill commented
I don't think we need to worry about the license. This example was modified from the official nest examples anyway

2022-03-22 20:35 UTC, merged